### ISSUE TITLE
Error when trying to run the tool

### ISSUE THREAD

**Issue by Elisecx** [Sitiaro/kikphisher#1]
It gives me some EOL error? I run it using ./kikphisher.sh and this is what it gives me

$ ./kikphisher.sh
./kikphisher.sh: line 7: $'\r': command not found
./kikphisher.sh: line 20: syntax error near unexpected token `$'{\r''
'/kikphisher.sh: line 20: `exit_on_signal_SIGINT() {

**Comment by Sitiaro** [comment]
I'll fix that in the next commit, go through README.md (from next time on), but here's the fix;

$ sed -i 's/\r//' kikphisher.sh

This remove trailing \r character that causes this error.

**Comment by enigmatic21** [comment]
This confuses me. Is it the whitespaces that cause this to happen? What's \r?

**Comment by Sitiaro** [comment]
Bash expects that end-of-line in a script is always and only a newline (\n) character, Unix-style, not a carriage return-newline combination (\r\n) like you normally see on Windows. Bash thinks the \r character is just an ordinary character at the end of the string and it returns this error.
