### ISSUE TITLE
Terminal freezes (fr this time)

### ISSUE THREAD

**Issue by Elisecx** [Sitiaro/kikphisher#2]
Sooo, the \r error got fixed but I encountered another issue. I navigated through the options and chose ngrok as port forwarding but it froze and my terminal got stuck on starting ngrok. Am I doing something wrong or is it the same for the others as well?

**Comment by Sitiaro** [comment]
Try re-cloning the repository. If that doesn't fix the issue then turn your hotspot on whilst using ngrok, that should definately fix the issue.

**Comment by Mizuwuki** [comment]
What does turning on the hotspot do?

**Comment by Sitiaro** [comment]
The hotspot in the Android device forms a complementary NAT that provides local IP addresses to the devices connected to the hotspot. 
Long story short, it helps w port-forwarding.

**Comment by Elisecx** [comment]
It worked, tyz
